### PR TITLE
Add New-ClassDefinitionFromObject and update docs

### PR DESCRIPTION
**Pull request by briantist**

### CODE REVIEW

**Comment by markwragg** [comment]
Happened upon this and think it may be useful for something similar I'm working on, however the object that I used it to create a class from has property names that include spaces (the object is built from an API call to a ticket system where some field names include spaces) and as a result the class definition was invalid.

It's an easy fix, I just changed `Name = $prop.Name` to `Name = "{$($prop.Name)}"`. but thought i'd flag it in case you thought it was important to include.

**Comment by dfinke** [comment]
@briantist Did a quick pass on your code. I'll take a deeper dive. Made think of this: https://www.powershellgallery.com/packages/ConvertToClass 

Good stuff

**Comment by briantist** [comment]
@dfinke well.. damn haha. What I did here is probably a little smaller in scope. There are some limits to what can be done here too since the whole point is to support casting, so no making properties mandatory through the use of constructors or things like that.

**Comment by dfinke** [comment]
This is cool. It'd great if you could work up a simple example and add it to the read me. And/Or create an examples folder and drop it in there. That way folks could kick the tires.

**Comment by briantist** [comment]
@dfinke Um.. I did. I added a whole section in the readme! :-p

**Pull request merged**
